#!/usr/bin/env bash
# This script installs and configures an nginx server on an ubuntu machine

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
