#!/usr/bin/env bash
# Update package list and install HAProxy
# Backup the original HAProxy configuration file
# Create a new HAProxy configuration 

sudo apt update
sudo apt install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo cat << EOF > /etc/haproxy/haproxy.cfg
global
    maxconn 4096
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend starhaven-project.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 155113-web-01 54.210.97.161:80 check
    server 155113-web-02 54.146.56.87:80 check
EOF

# Restart HAProxy service
sudo service haproxy restart
