#!/usr/bin/env bash
# This script is pinging 5 times the given as parameter ip adress.


if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ip="$1"

ping -c 5 "$ip" 
