#! /usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

i=1
while [ $i -lt 10 ]; do
	if [ $i == 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done

